apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-credentials
  namespace: argocd
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: github-repo-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: "https://github.com/grahamsutton"
        username: "{{ .username }}"
        password: "{{ .token }}"
  data:
  - secretKey: username
    remoteRef:
      key: github
      property: username
  - secretKey: token
    remoteRef:
      key: github
      property: token